services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin123!
    ports:
      - "1431:1431"
      - "1433:1433"
      - "1434:1434"